server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: cambio-microservice
          uri: lb://cambio-microservice
          predicates:
            - Path=/cambios/**
        - id: book-microservice
          uri: lb://book-microservice
          predicates:
            - Path=/books/**

