changeLogFile=classpath:/db/changelog/db.changelog.xml
driver=com.mysql.cj.jdbc.Driver
url=jdbc:mysql://localhost:3306/book_service?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
username=root
password=admin123
