name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Book Microservice Image
        working-directory: ./book-service
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Exchange Microservice Image
        working-directory: ./exchange-service
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Gateway Microservice Image
        working-directory: ./gateway-service
        run: mvn spring-boot:build-image -DskipTests

      - name: Build Registry Microservice Image
        working-directory: ./registry-service
        run: mvn spring-boot:build-image -DskipTests

